/*	@(#)table.c	1.3	*/
# include "mfile2"

# define AWD SNAME|SOREG|SCON

# define ANYSIGNED TPOINT|TINT|TLONG|TSHORT|TCHAR
# define ANYUSIGNED TUNSIGNED|TULONG|TUSHORT|TUCHAR
# define ANYFIXED ANYSIGNED|ANYUSIGNED
# define TWORD TINT|TUNSIGNED|TPOINT|TLONG|TULONG
# define TSMALL TSHORT|TUSHORT|TCHAR|TUCHAR

#undef INBREG
#undef INTBREG
#undef NBREG
#undef NBSL
#undef SBREG
#undef STBREG

#define INBREG	INAREG
#define INTBREG INTAREG
#define NBREG	NAREG
#define NBSL	NASL
#define SBREG	SAREG
#define STBREG	STAREG


struct optab  table[] = {

PCONV,	INAREG|INTAREG,
	SAREG|AWD,	TSMALL,
	SANY,	TPOINT,
		NAREG|NASL,	RESC1,
		"Zl",

	/* the following entry is to fix a problem with
	   the manner that the first pass handles the
	   type of a shift expression                 */
PCONV,	INAREG|INTAREG,
	SAREG|AWD,	TINT|TUNSIGNED,
	SANY,	TPOINT,
		NAREG|NASL,	RLEFT,
		"",

SCONV,	INTBREG|FORCC,
	SBREG,	TDOUBLE,
	SANY,	TDOUBLE,
		0,	RLEFT,
		"",

SCONV,	INTAREG|FORCC,
	SAREG,	TWORD,
	SANY,	TWORD,
		0,	RLEFT,
		"",

SCONV,	INTAREG,
	SAREG,	TFLOAT,
	SANY,	TDOUBLE,
		NAREG|NASL,	RESC1|RESCC,
		"Z3	fadd.dss\tTA1,r0,AL\n",

SCONV,	INTAREG,
	SAREG,	TDOUBLE,
	SANY,	TFLOAT,
		NAREG|NASL,	RESC1|RESCC,
		"Z3	fadd.ssd\tTA1,r0,AL\n",

SCONV,	INTAREG,
	SAREG,	ANYFIXED,
	SANY,	TFLOAT|TDOUBLE,
		NAREG|NASL,	RESC1|RESCC,
		"Z3	flt.ZRs\tTA1,AL\n",

SCONV,	INTAREG,
	SAREG,	TFLOAT|TDOUBLE,
	SANY,	ANYFIXED,
		NAREG|NASL,	RESC1|RESCC,
		"Z3	trnc.sZL	A1,AL\n",

SCONV,	INTAREG,
	SCON,	TPOINT,
	SANY,	TSMALL,
		NAREG,	RESC1|RESCC,
		"ZO",

SCONV,	INTAREG,
	AWD,	TWORD|TSHORT|TUSHORT,
	SANY,	ANYFIXED,
		NAREG|NASL,	RESC1|RESCC,
		/*"	ld.ZRZM\tA1,ZZ\n",*/
		"ZZ",

SCONV,	INTAREG,
	SAREG,	TWORD|TSHORT|TUSHORT,
	SANY,	TSMALL,
		NAREG|NASL,	RESC1|RESCC,
		"ZO",

INIT,	FOREFF,
	SCON,	TANY,
	SANY,	TWORD,
		0,	RNOP,
		"	word	CL\n",

INIT,	FOREFF,
	SCON,	TANY,
	SANY,	TSHORT|TUSHORT,
		0,	RNOP,
		"	half	CL\n",

INIT,	FOREFF,
	SCON,	TANY,
	SANY,	TCHAR|TUCHAR,
		0,	RNOP,
		"	byte	CL\n",

	/* for the use of fortran only */

GOTO,	FOREFF,
	SCON,	TANY,
	SANY,	TANY,
		0,	RNOP,
		"	br	CL\n",

GOTO,	FOREFF,
	SAREG,	TANY,
	SANY,	TANY,
		0,	RNOP,
		"	jmp	AL\n",

STASG,	FORARG,
	SNAME|SOREG,	TANY,
	SCON|SAREG,	TANY,
		0,	RNULL,
		"	subu	r31,r31,ZT\nZS",

STASG,	FOREFF,
	SNAME|SOREG,	TANY,
	SCON|SAREG,	TANY,
		0,	RNOP,
		"ZS",

STASG,	INAREG,
	SNAME|SOREG,	TANY,
	SCON,	TANY,
		NAREG,	RESC1,
		"ZSZr",

STASG,	INAREG,
	SNAME|SOREG,	TANY,
	SAREG,	TANY,
		NTEMP,	RRIGHT,
		"	st	AR,A1\nZS	ld	AR,A1\n",

/* match register fields only */
FLD,	INAREG|INTAREG,
	SANY,	TANY,
	SFLD,	ANYSIGNED,
		NAREG|NASL,	RESC1,
		"Zr	ext	A1,A1,S<H>\n",

FLD,	INAREG|INTAREG,
	SANY,	TANY,
	SFLD,	ANYUSIGNED,
		NAREG|NASL,	RESC1,
		"Zr	extu	A1,A1,S<H>\n",

OPLOG,	FORCC,
	SAREG,		TWORD,
	SAREG|SCON,	TWORD,
		NAREG,	RESCC,
		"ZUZP",

OPLOG,	FORCC,
	SAREG,	TSHORT|TUSHORT,
	SAREG,	TSHORT|TUSHORT,
		0,	RESCC,
		"ZUZP",

OPLOG,	FORCC,
	SAREG,	TCHAR|TUCHAR,
	SAREG,	TCHAR|TUCHAR,
		0,	RESCC,
		"ZUZP",

OPLOG,	FORCC,
	SAREG,	TSHORT|TUSHORT,
	SSCON,	TANY,
		0,	RESCC,
		"ZUZP",

OPLOG,	FORCC,
	SAREG,	TCHAR|TUCHAR,
	SCCON,	TANY,
		0,	RESCC,
		"ZUZP",

OPLOG,	FORCC,
	SBREG,	TDOUBLE,
	SBREG,	TDOUBLE,
		0,	RESCC,
		"ZUZP",

OPLOG,	FORCC,
	SBREG,	TFLOAT,
	SBREG,	TFLOAT,
		0,	RESCC,
		"ZUZP",

CCODES,	INAREG|INTAREG,
	SANY,	TANY,
	SANY,	TANY,
		NAREG,	RESC1,
		"ZN",

UNARY CALL,	INTAREG,
	SCON,	TANY,
	SANY,	TWORD|TCHAR|TUCHAR|TSHORT|TUSHORT,
		NAREG|NASL,	RESC1, /* should be register r2 */
		"	bsr	CL\nZC",

UNARY CALL,	INTAREG,
	SAREG,	TANY,
	SANY,	TWORD|TCHAR|TUCHAR|TSHORT|TUSHORT,
		NAREG|NASL,	RESC1,	/* should be r2 */
		"	jsr	AL\nZC",

UNARY CALL,	INTBREG,
	SCON,	TANY,
	SANY,	TFLOAT|TDOUBLE,
		NAREG|NASL,	RESC1, /* should be register r2 */
		"T	bsr	CL\nZC",

UNARY CALL,	INTBREG,
	SAREG,	TANY,
	SANY,	TFLOAT|TDOUBLE,
		NAREG|NASL,	RESC1,	/* should be r2 */
		"T	jsr	AL\nZC",

ASG LS,	INAREG|FOREFF,
	SAREG,	TWORD,
	SAREG|SCON,	ANYSIGNED|ANYUSIGNED,
		0,	RLEFT|RESCC,
		"	mak	AL,AL,ZX\n",

ASG LS,	INAREG|FOREFF,
	AWD,	TWORD,
	SAREG|SCON,	ANYSIGNED|ANYUSIGNED,
		NAREG,	RLEFT|RESCC,
		"Zl	mak	A1,A1,ZX\nZs",

LS,	INAREG|INTAREG,
	STAREG,	TWORD,
	SAREG|SCON,	ANYSIGNED|ANYUSIGNED,
		0,	RLEFT|RESCC,
		"	mak	AL,AL,ZX\n",

LS,	INAREG|INTAREG,
	SAREG,	TWORD,
	SAREG|SCON,	ANYSIGNED|ANYUSIGNED,
		NAREG|NASL,	RESC1|RESCC,
		"	mak	A1,AL,ZX\n",

LS,	INAREG|INTAREG,
	AWD,	TWORD,
	SAREG|SCON,	ANYSIGNED|ANYUSIGNED,
		NAREG|NASL,	RESC1|RESCC,
		"Zl	mak	A1,A1,ZX\n",

ASG RS,	INAREG|FOREFF,
	SAREG,	TWORD,
	SAREG|SCON,	ANYSIGNED|ANYUSIGNED,
		0,	RLEFT|RESCC,
		"	extZQ	AL,AL,ZX\n",

ASG RS,	INAREG|FOREFF,
	AWD,	TWORD,
	SAREG|SCON,	ANYSIGNED|ANYUSIGNED,
		NAREG,	RLEFT|RESCC,
		"Zl	extZQ	A1,A1,ZX\nZs",

RS,	INAREG|INTAREG,
	STAREG,	TWORD,
	SAREG|SCON,	ANYSIGNED|ANYUSIGNED,
		0,	RLEFT|RESCC,
		"	extZQ	AL,AL,ZX\n",

RS,	INAREG|INTAREG,
	SAREG,	TWORD,
	SAREG|SCON,	ANYSIGNED|ANYUSIGNED,
		NAREG|NASL,	RESC1|RESCC,
		"	extZQ	A1,AL,ZX\n",

RS,	INAREG|INTAREG,
	AWD,	TWORD,
	SAREG|SCON,	ANYSIGNED|ANYUSIGNED,
		NAREG|NASL,	RESC1|RESCC,
		"Zl	extZQ	A1,A1,ZX\n",

INCR,	FOREFF,
	AWD,	TANY,
	SCON,	TANY,
		NAREG,	RLEFT,
		"ZE",

DECR,	FOREFF,
	AWD,	TANY,
	SCON,	TANY,
		NAREG,	RLEFT,
		"ZE",

INCR,	FOREFF,
	SAREG,	TWORD,
	SCON,	TANY,
		0,	RLEFT,
		"ZE",

DECR,	FOREFF,
	SAREG,	TWORD,
	SCON,	TANY,
		0,	RLEFT,
		"ZE",

/* INCR and DECR for SAREG T[U]CHAR|T[U]SHORT matched by ASG OPSIMP etc */

INCR,	INAREG|INTAREG,
	AWD,	TANY,
	SCON,	TANY,
		2*NAREG,	RESC1,
		"ZD",

DECR,	INAREG|INTAREG,
	AWD,	TANY,
	SCON,	TANY,
		2*NAREG,	RESC1,
		"ZD",

INCR,	INAREG|INTAREG,
	SAREG,	TWORD|TUSHORT|TUCHAR,
	SCON,	TANY,
		NAREG,	RESC1,
		"ZD",

DECR,	INAREG|INTAREG,
	SAREG,	TWORD|TUSHORT|TUCHAR,
	SCON,	TANY,
		NAREG,	RESC1,
		"ZD",

ASSIGN,	INBREG|FOREFF,
	SBREG|AWD,	TDOUBLE|TFLOAT,
	SBREG|AWD,	TDOUBLE|TFLOAT,
		NBREG,	RLEFT|RRIGHT|RESCC,
		"TZA",

ASSIGN,	INAREG|FOREFF,
	SAREG|AWD,	ANYFIXED,
	SAREG|AWD,	ANYFIXED,
		NAREG,	RLEFT|RRIGHT|RESCC,
		"ZA",

ASSIGN,	INAREG|FOREFF,
	SFLD,	TANY,
	SAREG,	TWORD,
		2*NAREG,	RRIGHT,
		"Zl\tclr\tA1,A1,S<H>\n\tmak\tA2,AR,S<H>\n\tor\tA1,A1,A2\nZs",
		
ASSIGN,	INAREG|FOREFF,
	SFLD,	TANY,
	SICON,	TWORD,
		NAREG,	RRIGHT,
		"ZlZGZs",
		
/* dummy UNARY MUL entry to get U* to possibly match OPLTYPE */
UNARY MUL,	FOREFF,
	SCC,	TANY,
	SCC,	TANY,
		0,	RNULL,
		"	HELP HELP HELP\n",

REG,	INTEMP,
	SANY,	TANY,
	SBREG,	TDOUBLE,
		2*NTEMP,	RESC1,
		"	st.d	AR,A1\n",

REG,	INTEMP,
	SANY,	TANY,
	SAREG|SBREG,	TANY,
		NTEMP,	RESC1,
		"	st	AR,A1\n",

#ifdef FORTVAX
 REG,	FORARG,
	SANY,	TANY,
	SAREG,	TFLOAT,
		0,	RNULL,
		"	cvtfd	AR,-(sp)\n",

REG,	FORARG,
	SANY,	TANY,
	SAREG,	TDOUBLE,
		0,	RNULL,
		"	movZR	AR,-(sp)\n",
#endif

OPLEAF,	FOREFF,
	SANY,	TANY,
	SAREG|SBREG|AWD,	TANY,
		0,	RLEFT,
		"",

OPLTYPE,	INBREG|INTBREG,
	SANY,	TANY,
	SANY,	TFLOAT|TDOUBLE,
		NBREG|NASR,	RESC1,
		"TZA",

OPLTYPE,	INAREG|INTAREG,
	SANY,	TANY,
	SANY,	ANYFIXED,
		NAREG|NASR,	RESC1,
		"ZA",

OPLTYPE,	FORCC,
	SANY,	TANY,
	SAREG,	ANYFIXED,
		0,	RESCC,
		"ZV",

OPLTYPE,	FORCC,
	SANY,	TANY,
	SANY,	ANYFIXED,
		NAREG|NASR,	RESCC,
		"ZrZV",

OPLTYPE,	FORCC,
	SANY,	TANY,
	SBREG,	TFLOAT|TDOUBLE,
		0,	RESCC,
		"Z3	fcmp.sZRs	r13,AR,r0\nZn",

OPLTYPE,	FORCC,
	SANY,	TANY,
	SANY,	TFLOAT|TDOUBLE,
		NBREG,	RESCC,
		"ZrZ3	fcmp.sZRs	r13,A1,r0\nZn",

OPLTYPE,	FORARG,
	SANY,	TANY,
	SAREG,	ANYFIXED,
		0,	RNULL,
		"ZY",

OPLTYPE,	FORARG,
	SANY,	TANY,
	AWD,	ANYFIXED,
		NAREG,	RNULL,
		"ZrZY",

OPLTYPE,	FORARG,
	SANY,	TANY,
	SBREG,	TDOUBLE,
		0,	RNULL,
		"ZY",

OPLTYPE,	FORARG,
	SANY,	TANY,
	AWD,	TDOUBLE,
		NBREG,	RNULL,
		"ZrZY",

OPLTYPE,	FORARG,
	SANY,	TANY,
	SAREG,	TFLOAT,
		NAREG|NASR,	RNULL,
		"Z3	fadd.dss	A1,r0,AR\nZY",

UNARY MINUS,	INTAREG,
	SAREG,	TINT|TUNSIGNED|TLONG|TULONG,
	SANY,	TANY,
		NAREG|NASL,	RESC1|RESCC,
		"	subu	A1,r0,AL\n",

UNARY MINUS,	INTAREG,
	AWD,	TINT|TUNSIGNED|TLONG|TULONG,
	SANY,	TANY,
		NAREG|NASL,	RESC1|RESCC,
		"Zl	subu	A1,r0,A1\n",

UNARY MINUS,	INTBREG,
	SBREG,	TFLOAT|TDOUBLE,
	SANY,	TANY,
		NBREG,	RESC1|RESCC,
		"TZ3	fsub.ZLsZL	A1,r0,AL\n",

UNARY MINUS,	INTBREG,
	AWD,	TFLOAT|TDOUBLE,
	SANY,	TANY,
		NBREG,	RESC1|RESCC,
		"TZlZ3	fsub.ZLsZL	A1,r0,A1\n",

COMPL,	INTAREG,
	SAREG,	TINT|TUNSIGNED,
	SANY,	TANY,
		NAREG,	RESC1|RESCC,
		"	subu	A1,r0,1\n	xor	A1,A1,AL\n",

COMPL,	INTAREG,
	SAREG|AWD,	ANYFIXED,
	SANY,	TANY,
		2*NAREG,	RESC1|RESCC,
		"Zl	subu	A2,r0,1\n	xor	A1,A1,A2\n",

ASG OPMUL,	INAREG|FOREFF,
	SAREG,	TINT|TUNSIGNED|TLONG|TULONG,
	SAREG,	TINT|TUNSIGNED|TLONG|TULONG,
		0,	RLEFT|RESCC,
		"	OLZW	AL,AL,AR\n",

ASG OPMUL,	INAREG|FOREFF,
	SAREG,		TINT|TUNSIGNED|TLONG|TULONG,
	SMULCON,	TINT|TUNSIGNED|TLONG|TULONG,
		0,	RLEFT|RESCC,
		"	OLZW	AL,AL,CR\n",

OPMUL,	INAREG|INTAREG,
	STAREG,		TINT|TUNSIGNED|TLONG|TULONG,
	SMULCON,	TINT|TUNSIGNED|TLONG|TULONG,
		0,	RLEFT|RESCC,
		"	OLZW	AL,AL,CR\n",

OPMUL,	INAREG|INTAREG,
	STAREG,	TINT|TUNSIGNED|TLONG|TULONG,
	SAREG,	TINT|TUNSIGNED|TLONG|TULONG,
		0,	RLEFT|RESCC,
		"	OLZW	AL,AL,AR\n",

OPMUL,	INAREG|INTAREG,
	SAREG,		TINT|TUNSIGNED|TLONG|TULONG,
	SMULCON,	TINT|TUNSIGNED|TLONG|TULONG,
		NAREG|NASL,	RESC1|RESCC,
		"	OLZW	A1,AL,CR\n",

OPMUL,	INAREG|INTAREG,
	SAREG,		TINT|TUNSIGNED|TLONG|TULONG,
	SAREG,		TINT|TUNSIGNED|TLONG|TULONG,
		NAREG|NASL,	RESC1|RESCC,
		"	OLZW	A1,AL,AR\n",

ASG MOD,	INAREG|INTAREG|FOREFF,
	SAREG,	TINT|TUNSIGNED|TLONG|TULONG,
	SAREG,	TINT|TUNSIGNED|TLONG|TULONG,
		NAREG,	RLEFT|RESCC,
		"\tdivZW	A1,AL,AR\n\tmul	A1,A1,AR\n\tsubu	AL,AL,A1\n",

MOD,	INAREG|INTAREG,
	SAREG,	TINT|TUNSIGNED|TLONG|TULONG,
	SAREG,	TINT|TUNSIGNED|TLONG|TULONG,
		NAREG,	RESC1,
		"\tdivZW	A1,AL,AR\n\tmul	A1,A1,AR\n\tsubu	A1,AL,A1\n",

ASG OPSIMP,	INAREG|FOREFF,
	SAREG,	TWORD,
	SAREG,	ANYFIXED,
		0,	RLEFT|RESCC,
		"	OL	AL,AL,AR\n",

ASG OPSIMP,	INAREG|FOREFF,
	SAREG,	TSMALL,
	SAREG,	ANYFIXED,
		0,	RLEFT|RESCC,
		"	OL	AL,AL,AR\nZK",

ASG OPSIMP,	INAREG|FOREFF,
	AWD,	TWORD,
	SAREG,	ANYFIXED,
		NAREG,	RLEFT|RESCC,
		"Zl\tOL	A1,A1,AR\nZs",

ASG OPSIMP,	INAREG|FOREFF,
	AWD,	ANYFIXED,
	SAREG,	ANYFIXED,
		NAREG,	RLEFT|RESCC,
		"Zl\tOL	A1,A1,AR\nZs",

ASG OPSIMP,	INAREG|FOREFF,
	SAREG,	TWORD,
	SPCON16,	ANYFIXED,
		0,	RLEFT|RESCC,
		"	OW	AL,AL,CR\n",

ASG OPSIMP,	INAREG|FOREFF,
	SAREG,	TSMALL,
	SPCON16,	ANYFIXED,
		0,	RLEFT|RESCC,
		"	OL	AL,AL,CR\nZK",	/* no I ops here */

ASG OPSIMP,	INAREG|FOREFF,
	AWD,	TWORD,
	SPCON16,	ANYFIXED,
		NAREG,	RLEFT|RESCC,
		"Zl\tOW	A1,A1,CR\nZs",

ASG OPSIMP,	INAREG|FOREFF,
	AWD,	ANYFIXED,
	SPCON16,	ANYFIXED,
		NAREG,	RLEFT|RESCC,
		"Zl\tOW	A1,A1,CR\nZs",

OPSIMP,	INAREG|INTAREG,
	SAREG,		TWORD,
	SAREG,	TWORD,
		NAREG|NASL,	RESC1|RESCC,
		"	OL	A1,AL,AR\n",

OPSIMP,	INAREG|INTAREG,
	SAREG,		TSMALL,
	SAREG,	ANYFIXED,
		NAREG|NASL,	RESC1|RESCC,
		"	OL	A1,AL,AR\n",

OPSIMP,	INAREG|INTAREG,
	SAREG,		TWORD,
	SPCON16,	TWORD,
		NAREG|NASL,	RESC1|RESCC,
		"	OW	A1,AL,CR\n",

OPSIMP,	INAREG|INTAREG,
	SAREG,		TSMALL,
	SPCON16,	ANYFIXED,
		NAREG|NASL,	RESC1|RESCC,
		"	OW	A1,AL,CR\n",

ASG OPFLOAT,	INBREG|FOREFF,
	SBREG,	TDOUBLE|TFLOAT,
	SBREG,	TDOUBLE|TFLOAT,
		0,	RLEFT|RESCC,
		"TZ3	fOD.ZLZLZR	AL,AL,AR\n",

OPFLOAT,	INBREG|INTBREG,
	SBREG,	TDOUBLE|TFLOAT,
	SBREG,	TDOUBLE|TFLOAT,
		NBREG|NASL|NASR,	RESC1|RESCC,
		"TZ3	fOD.ZHZLZR	A1,AL,AR\n",


	/* Default actions for hard trees ... */

# define DF(x) FORREW,SANY,TANY,SANY,TANY,REWRITE,x,""

UNARY MUL, DF( UNARY MUL ),

INCR, DF(INCR),

DECR, DF(INCR),

ASSIGN, DF(ASSIGN),

STASG, DF(STASG),

FLD, DF(FLD),

OPLEAF, DF(NAME),

OPLOG,	FORCC,
	SANY,	TANY,
	SANY,	TANY,
		REWRITE,	BITYPE,
		"",

OPLOG,	DF(NOT),

COMOP, DF(COMOP),

INIT, DF(INIT),

OPUNARY, DF(UNARY MINUS),


ASG OPANY, DF(ASG PLUS),

OPANY, DF(BITYPE),

FREE,	FREE,	FREE,	FREE,	FREE,	FREE,	FREE,	FREE,	"help; I'm in trouble\n" };

