#	Copyright (c) 1984 AT&T
#	  All Rights Reserved

#	THIS IS UNPUBLISHED PROPRIETARY SOURCE CODE OF AT&T
#	The copyright notice above does not evidence any
#	actual or intended publication of such source code.

#ident	"@(#)uname:uname.mk	1.1"

#	Makefile for uname 

ROOT =

DIR = $(ROOT)/bin

INC = $(ROOT)/usr/include

LDFLAGS = -s $(LDLIBS)

CFLAGS = -O -I$(INC)

STRIP = strip

SIZE = size

#top#
# Generated by makefile 1.47

MAKEFILE = uname.mk

MAINS = uname

OBJECTS =  uname.o

SOURCES =  uname.c

ALL:		$(MAINS)

uname:	uname.o
	$(CC) $(CFLAGS) -o uname uname.o $(LDFLAGS)

uname.o:	 $(INC)/stdio.h \
		 $(INC)/sys/utsname.h \
		 $(INC)/string.h	\
		 $(INC)/sys/types.h \
		 $(INC)/sys/sys3b.h 
	-if ns32332; then \
		$(CC) $(CFLAGS) -Dpm200 -c uname.c; \
	elif ns32000; then \
		$(CC) $(CFLAGS) -Dpm100 -c uname.c; \
	elif clipper; then \
		$(CC) $(CFLAGS) -Dpm300 -c uname.c; \
	elif m88k; then \
		$(CC) $(CFLAGS) -Dpm400 -c uname.c; \
	fi

GLOBALINCS = $(INC)/stdio.h \
	$(INC)/string.h \
	$(INC)/sys/immu.h \
	$(INC)/sys/param.h \
	$(INC)/sys/sys3b.h \
	$(INC)/sys/types.h \
	$(INC)/sys/utsname.h 


clean:
	rm -f $(OBJECTS)

clobber:
	rm -f $(OBJECTS) $(MAINS)

newmakefile:
	makefile -m -f $(MAKEFILE)  -s INC $(INC)
#bottom#

all : ALL

install: ALL
	cpset $(MAINS) $(DIR)

size: ALL
	$(SIZE) $(MAINS)

strip: ALL
	$(STRIP) $(MAINS)

#	These targets are useful but optional

partslist:
	@echo $(MAKEFILE) $(SOURCES) $(LOCALINCS)  |  tr ' ' '\012'  |  sort

productdir:
	@echo $(DIR) | tr ' ' '\012' | sort

product:
	@echo $(MAINS)  |  tr ' ' '\012'  | \
	sed 's;^;$(DIR)/;'

srcaudit:
	@fileaudit $(MAKEFILE) $(LOCALINCS) $(SOURCES) -o $(OBJECTS) $(MAINS)
